[book]
title = "Line Following Maze Solver"
description = "Task curriculum: Arduino-based line follower maze-solving bot"
authors = ["e-Yantra"]
language = "en"
src = "src"

[build]
build-dir = "book"
create-missing = false

[output.html]
default-theme = "navy"             
preferred-dark-theme = "navy"
no-section-label = true   

[output.html.fold]
enable = true
level = 0